### ISSUE TITLE
Ни на одну букву нельзя навести курсор?

### ISSUE THREAD

**Issue by pqr** [spb-frontend/holyjs-2017-competition#1]
В задании написано: «после того как они разлетелись при наведению на любую букву все буквы меняют позиции», а ниже указано противоположное условие: «Ни на одну букву нельзя навести курсор» - не понятно, что имеется ввиду? Внесите ясность.

**Comment by nd0ut** [comment]
Я полагаю, что имеется в виду, что при попытке навести курсор на буквы, они должны от него убегать.

**Comment by nd0ut** [comment]
Я полагаю, что имеется в виду, что при попытке навести курсор на буквы, они должны от него убегать.  (я просто мимо проходил, к организаторам не имею отношения)

**Comment by prosv** [comment]
Привет! Да, имеется в виду "при попытке наведения", мы поправим в задании.
